version: '3.8'

services:
  app:
    build: .
    container_name: bouquetshop_app
    ports:
      - "8501:8501"
    volumes:
      - ./test-driven-dev:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: bouquetshop

  db:
    image: mysql:8.0
    container_name: bouquetshop_db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bouquetshop
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
